config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"

  get    "login",  to: "sessions#new"
  post   "login",  to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "signup", to: "users#new"
  resources :users, only: [:index, :show, :edit, :create, :update, :destroy] do
    member do
      get :following
      get :followers
    end
  end
  resources :tweets, path: "chirps"
  resource  :relationship, only: [:create, :destroy]
  resolve("Relationship") { :relationship }

  resources :conversations do
    resources :messages
  end

  get "help",    to: "static_pages#help"
  get "about",   to: "static_pages#about"
  get "contact", to: "static_pages#contact"
end

app/views/shared/_error_messages.html.erb
<div class="alert alert-danger">
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_follow.html.erb
<%= form_with model: current_user.active_relationships.new(followed: user), local: true do |form| %>
  <%= form.hidden_field :followed_id %>
  <%= form.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_profile.html.erb
<div class="profile clearfix">
  <%= link_to gravatar_for(@user, size: 75), @user %>
  <div><%= link_to @user.name, @user %></div>
  <div><%= @user.email %></div>

  <% if logged_in? && !current_user?(@user) %> 
    <div id="follow_form">
      <% if current_user.following?(@user) %>
        <%= render 'shared/unfollow', user: @user %>
      <% else %>
        <%= render 'shared/follow', user: @user %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

<div class="stats">
  <table>
  <tr>
    <th>Chirps</th>
    <th>Following</th>
    <th>Followers</th>
  </tr>
  <tr>
    <td><%= link_to @user.tweets.count, user_path(@user) %></td>
    <td><%= link_to @user.following.count, following_user_path(@user) %></td>
    <td><%= link_to @user.followers.count, followers_user_path(@user) %></td>
  </tr>
  </table>
</div>

app/views/shared/_tweet_form.html.erb
<div class="tweet-box">
  <%= form_with model: current_user.tweets.new, local: true do |form| %>
    <div class="field">
      <%= form.text_area :content, placeholder: "Compose new Chirp..." %>
    </div>
    <div class="btn-toolbar justify-content-between">
      <div class="btn-group">
        <%= form.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
      </div>
      <div class="btn-group">
        <%= form.submit "Post to the public", class: "btn btn-large btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_unfollow.html.erb
<%= form_with model: current_user.active_relationships.find_by(followed: user), local: true, html: { method: :delete } do |form| %>
  <%= form.hidden_field :follower_id  %>
  <%= form.hidden_field :followed_id  %>
  <%= form.submit "Unfollow", class: "btn btn-large btn-default" %>
<% end %>

app/views/shared/_user_info.html.erb
<% @user ||= current_user  %>

<%= render 'shared/profile' %>
<%= render 'shared/stats' %>
<%= render 'shared/tweet_form' %>