config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"

  get    "login",  to: "sessions#new"
  post   "login",  to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "signup", to: "users#new"
  resources :users, only: [:index, :show, :edit, :create, :update, :destroy] do
    member do
      get :following
      get :followers
    end
  end
  resources :tweets, path: "chirps"
  resource  :relationship, only: [:create, :destroy]
  resolve("Relationship") { :relationship }

  resources :conversations do
    resources :messages
  end

  get "help",    to: "static_pages#help"
  get "about",   to: "static_pages#about"
  get "contact", to: "static_pages#contact"
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    if logged_in?
      @tweets = current_user.feed.includes(:user).with_attached_image.paginate(page: params[:page], per_page: 6)
    end
  end
end

app/views/home/index.html.erb
<div class="row">
  <% if logged_in? %>
    <% provide(:title, 'Home') %>

    <aside class="col-md-4">
      <section>
        <%= render 'shared/user_info' if logged_in? %>
      </section>
    </aside>
    <div class="col-md-8">
      <div class="timeline">
        <h2 class="title">Chirps</h2>
        <% if @tweets.any? %>
        <ol class="tweets">
          <%= render @tweets %>
          <div class="paginate">
            <%=will_paginate(@tweets, :previous_label => "&laquo;Previous", :next_label => "Next &raquo;") %>
          </div>
        </ol>
        <% end %>
      </div>
    </div>
  <% else %>
    <% provide(:title, 'Welcome') %>

    <div class="col-md-6 col-md-offset-3 one-col">
      <h1>Welcome to <strong>Chirp</strong></h1>
      <%= image_tag("chirp_logo.png", size: 150) %>
      <p> See what’s happening in the world right now</p>
      <%= link_to 'Sign up', signup_path, class: "btn btn-primary" %>
      <%= link_to 'Log in', login_path, class: "btn btn-default" %>
    </div>
  <% end %>
</div>