config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"

  get    "login",  to: "sessions#new"
  post   "login",  to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "signup", to: "users#new"
  resources :users, only: [:index, :show, :edit, :create, :update, :destroy] do
    member do
      get :following
      get :followers
    end
  end
  resources :tweets, path: "chirps"
  resource  :relationship, only: [:create, :destroy]
  resolve("Relationship") { :relationship }

  resources :conversations do
    resources :messages
  end

  get "help",    to: "static_pages#help"
  get "about",   to: "static_pages#about"
  get "contact", to: "static_pages#contact"
end

app/views/layouts/_footer.html.erb
<hr>
<footer class="footer">
  <%= link_to "Help", help_path %>
  <%= link_to "About", about_path  %>
  <%= link_to "Contact", contact_path %>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <%= link_to root_path do %>
        <div class= "navbar-brand" >
          <strong> Chirp </strong>
        </div>
          <%= image_tag("chirp_logo.png", size: 45) %>
      <% end %>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span> 
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right header-menu">
        <% if logged_in? %>
          <li>
            <%= link_to users_path do %>
              <%= icon("users") %>
              <span>Users</span>
            <% end %>
          </li>
          <li>
            <%= link_to tweets_path do %>
              <%= icon("comment") %>
              <span>Chirps</span>
            <% end %>
           <li>
            <%= link_to conversations_path(current_user) do %>
              <%= icon("paper-plane") %>
              <span>Messages</span>
            <% end %>
          </li>
          </li>
          <li>
            <%= link_to current_user do %>
              <%= icon("user") %>
              <span>My Profile</span>
            <% end %>
          </li>
          <li>
            <%= link_to edit_user_path(current_user) do %>
              <%= icon("cog") %>
              <span>Setting</span>
            <% end %>
          </li>
          <li>
            <%= link_to logout_path, method: "delete" do %>
              <%= icon("sign-out") %>
              <span>Log out</span>
            <% end %>
          </li>
        <% else %>
          <% unless params[:controller] == 'static_pages' %> 
            <li>
              <%= link_to login_path do %>
                <%= icon("users") %>
                <span>Users</span>
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <%= icon("comment") %>
                <span>Chrips</span>
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <%= icon("sign-in") %>
                <span>Sign in</span>
              <% end %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= stylesheet_pack_tag "application" %>
    <%= javascript_pack_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%#<%= debug(params) if Rails.env.development? %>
    </div>
    <!--
    <script>
      var hrefElems = document.querySelectorAll("[href^='/']");
      var srcElems = document.querySelectorAll("[src^='/']");
      hrefElems.forEach(function(elem) {
        elem.setAttribute('href', window.location.href.split('/').slice(0,4).join('/')+elem.getAttribute('href'))
      });
      srcElems.forEach(function(elem) {
        elem.setAttribute('src', window.location.href.split('/').slice(0,4).join('/')+elem.getAttribute('src'))
      });
    </script>
    -->
  </body>
</html>